# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: colaboflow/audit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='colaboflow/audit.proto',
  package='colabo.flow',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x63olaboflow/audit.proto\x12\x0b\x63olabo.flow\",\n\x12SubmitAuditRequest\x12\n\n\x02n1\x18\x01 \x01(\x05\x12\n\n\x02n2\x18\x02 \x01(\x05\"\x1e\n\x10SubmitAuditReply\x12\n\n\x02n1\x18\x01 \x01(\x05\x32S\n\x05\x41udit\x12J\n\x06submit\x12\x1f.colabo.flow.SubmitAuditRequest\x1a\x1d.colabo.flow.SubmitAuditReply\"\x00\x62\x06proto3')
)




_SUBMITAUDITREQUEST = _descriptor.Descriptor(
  name='SubmitAuditRequest',
  full_name='colabo.flow.SubmitAuditRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n1', full_name='colabo.flow.SubmitAuditRequest.n1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n2', full_name='colabo.flow.SubmitAuditRequest.n2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=83,
)


_SUBMITAUDITREPLY = _descriptor.Descriptor(
  name='SubmitAuditReply',
  full_name='colabo.flow.SubmitAuditReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n1', full_name='colabo.flow.SubmitAuditReply.n1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['SubmitAuditRequest'] = _SUBMITAUDITREQUEST
DESCRIPTOR.message_types_by_name['SubmitAuditReply'] = _SUBMITAUDITREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubmitAuditRequest = _reflection.GeneratedProtocolMessageType('SubmitAuditRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUBMITAUDITREQUEST,
  __module__ = 'colaboflow.audit_pb2'
  # @@protoc_insertion_point(class_scope:colabo.flow.SubmitAuditRequest)
  ))
_sym_db.RegisterMessage(SubmitAuditRequest)

SubmitAuditReply = _reflection.GeneratedProtocolMessageType('SubmitAuditReply', (_message.Message,), dict(
  DESCRIPTOR = _SUBMITAUDITREPLY,
  __module__ = 'colaboflow.audit_pb2'
  # @@protoc_insertion_point(class_scope:colabo.flow.SubmitAuditReply)
  ))
_sym_db.RegisterMessage(SubmitAuditReply)



_AUDIT = _descriptor.ServiceDescriptor(
  name='Audit',
  full_name='colabo.flow.Audit',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=117,
  serialized_end=200,
  methods=[
  _descriptor.MethodDescriptor(
    name='submit',
    full_name='colabo.flow.Audit.submit',
    index=0,
    containing_service=None,
    input_type=_SUBMITAUDITREQUEST,
    output_type=_SUBMITAUDITREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUDIT)

DESCRIPTOR.services_by_name['Audit'] = _AUDIT

# @@protoc_insertion_point(module_scope)
